### PR TITLE
Mylist proxy

### PR DESCRIPTION
**Pull request by dcow**
Update project so that students may/must implement the List interface with a class named MyList.  This implementation is then used by the ListView's adapter.

### CODE REVIEW

**Comment by rebelsky** [comment]
Hi David.  Is this something that you're working with Lea on?  MyList isn't the best of names.

**Comment by dcow** [comment]
Lea asked for an example of how to rework the current code so that a student could implement the List interface and have their implementation used by the current framework.  MyList is named as such so students know which Java file they're  supposed to touch.  If you would like to provide an alternate name I can update the pull request.

**Comment by rebelsky** [comment]
They are implementing their own lists _before_ they learn about the collections framework (at least I think it's before).  So their code should not rely on that framework at all.  I'll need to check the syllabus, but they probably shouldn't even be writing generic code at this point - I think it's right when they're writing generics.

The natural name for the class is "List", because that's what it is.  The package name should distinguish between the standard List class and their list class.   If we're not doing generics, then IncidentList is probably the right name, since they're make a list of incidents.

But I don't really know what Lea's doing with it.

**Comment by dcow** [comment]
So they should never see the current implementation of MyList (beyond just deleting everything in that file if that isn't done for them).  The decorator/proxy is only provided so the code remains in a functioning state.  It's really just to show Lea the concept of implementing the List interface and passing that implementation to system/framework code.    She was unsure of how to restructure the code so that a student could provide a custom implementation of a data structure in a way that will still work with the framework widgets.

**Comment by rebelsky** [comment]
Okay, this should probably be ListProxy (or even StudentListProxy, since it's a proxy to the student's list class).  I don't know enough of the Android framework, but it strikes me that you want something like

```
public class StudentIncidentListProxy implements List<Incident> {
    IncidentList proxy;
    
    public StudentIncidentListProxy() {
        this.proxy = new IncidentList();
    } // StudentIncidentListProxy()
```

    
        public void add(Incident i) {
             this.proxy.add(i);
        } // add (incident)
    } // class StudentIncidentListProxy

I'd then have a stub class for IncidentList that students would fill in

```
public class IncidentList {
     public IncidentList() {
          // STUB
     } // IncidentList
    public void add(Incident i) {
        // STUB
    } // add
   public Incident get() {
         return null; // STUB
        }
    ....
} // class IncidentList
```

Does that make sense?

**Comment by rebelsky** [comment]
Sorry about the formatting.  GitHub doesn't like me today.

**Comment by dcow** [comment]
We're not on the same page.  This is partially my fault.  

My intent was that students would write a List class that implements the List interface.  In order to keep the code compiling, I provided an implementation of the List class (that implements the List interface) which is simply a proxy for an ArrayList (or, which simply forwards all its methods to the proxied object).  

What you are suggesting is necessary if you don't want students implementing the entire Java collections List interface and want to provide your own interface.  In that case, you need to write a class that wraps the more simple interface you decide on for the students, and then translates its functionality into the Java collections List interface (an adapter in the sense of the adapter pattern).

**Comment by rebelsky** [comment]
I don't want students writing to the Java collections framework, which I think too often takes a "kitchen sink" approach to design.  My goal is that they design and implement small, clean, data structures.

I'm bad at the proxy/adapter/wrapper dichotomy.  I would have said that what I was writing was a wrapper class, and I used proxy because that's what you were using, but it does seem adapter is reasonable.

**Comment by rebelsky** [comment]
Anyway, I'm happy to incorporate your code into this.  I was just trying to figure out what was going on.  (And I got the pull request to start it all off.)   Let me know.  In any case, it sounds like I'm going to need to do a significant redesign to match my pedagogical goals.

**Comment by dcow** [comment]
Agreed about the collections interface and your desired approach.  Yeah I don't the know exact distinction either, I generally go with 1:1 being a proxy, and 1:n (where n includes 1) being an adapter/wrapper/facade if data is being coerced into some other form or multiple functional units are being combined.  (Just looked it up and it would seem that intent is, indeed, the general distinction.)  Either way, I can update the process so @leamars can see an example of how you would like it done.

In terms of a significant redesign, I think it would be really cool to write a Java Annotation that can be applied to a Runnable which will run the Runnable in an Android environment.

``` java
@RunInAndroid
public class HelloDalvik implements Runnable {
    @Override public void run() {
        System.out.println("The Dalvik VM executed this code!");
    }
}
```

Problem with this is the usefulness falls off quickly as you can't interface with Android at all.  The solution might be to provide the Context to the Runnable:

``` java
@RunInAndroid
public class HelloDalvik implements AndroidRunnable {
    @Override public void run(Context runtimeContext) {
        Toast.makeText(runtimeContext, "The Dalvik VM executed this code!", Toast.LENGTH_LONG).show();
    }
}
```

This would allow you to hide the entire android environment for awhile.  However, once you need to start actually writing Android code you need to understand the framework + design conventions.  

If you are wanting to have students be changing parts of an already existing application though (as it currently is) then, yes, a lot of adapters/wrappers will need to be written so that you can plug the student code into the framework widgets.  In fact, it's probably easiest to, instead of wrapping everything in an adapter that translates to the a Java collections List, simply write the actual adapter that you pass to a View such that it can handle the students' data structures.

**Comment by dcow** [comment]
And yeah I don't care if you use my code, this is merely an example based on what I though the desired result was.

**Comment by dcow** [comment]
It’s funny how new UX brings to light a 7yr old PR.

**Comment by leamars** [comment]
What a blast from the past :D

**Pull request closed without merging**
